### ISSUE TITLE
Pipeline fails to untar the downloaded tar file from cyverse

### ISSUE THREAD

**Issue by Travis-Simmons** [phytooracle/automation#112]
The pipelines are failing to automatically untar the data. However, if you untar it manually and launch the pipelines they work. This is an issue with all S12 pipelines.
![Screenshot from 2022-07-26 15-41-22](https://user-images.githubusercontent.com/64273464/181098625-55816146-cd48-43d7-a4a6-a8ac7f78b261.png)

**Comment by equant** [comment]
I'm not sure if this is it, but it looks like a line was deleted from `get_support_files()` that might be the problem...

```
<<<<<<< HEAD
        server_utils.untar_files([filename])


=======


    sensor = dictionary["tags"]["sensor"]

    if sensor == "stereoTop":
        sp.call("git clone https://github.com/ariyanzri/Lettuce_Image_Stitching.git", shell=True)
>>>>>>> main

**Comment by equant** [comment]
This is not just Season 12.  It has broken probably all pipelines.  I'm working on it.

**Comment by Travis-Simmons** [comment]
Seems like this is fixed?

**Comment by equant** [comment]
Maybe.  I'm worried that it's intermittent.
