### ISSUE TITLE
Issues with upload are occuring again - some experiencing it, others are not

### ISSUE THREAD

**Issue by emmanuelgonz** [phytooracle/automation#132]
The issue is with PO output being uploaded onto CyVerse DataStore. The upload seems to start as expected, but the upload is terminated ~ 1 hour later. This issue is not present for every team member - only Jeffrey, Sarthak, and Jordan have experienced it. The issue is present in 

To address this, we will create a new branch with the following changes: 
- Change upload command to "ssh -vvv "iput -V <command>" > this is to increase the verbosity of the terminal output 
- Run this new branch of POA on 2022-02-04__00-00-00 > this is to quickly determine if changes have resolved the issue

**Comment by jeffreydemieville** [comment]
Per HPC Support:

"1.	Both Emmanuel and I have a file in our accounts called ~/.ssh/config. In this file, ServerAliveInterval is defined. This is something that will send a signal to the server every n seconds to keep the connection alive. You could test if creating this file (using something like "touch ~/.ssh/config") and adding the following contents helps prevent your connection from being broken:

```
Host *
    ServerAliveInterval 30
```
"
Testing the pipeline with this change made on my account results in the expected files uploaded to the datastore without timeouts.

**Comment by jeffreydemieville** [comment]
Pull request #134 submitted to try option 2.

`2. Alternatively, if the above doesn't help, I might try adding a --progress flag to the iput command and allowing that to print to your output file. That should hopefully help keep your connection alive and prevent it from timing out.`

Request @emmanuelgonz to review and merge with branch #132.

**Comment by emmanuelgonz** [comment]
Branch has been merged with main. Issue closed.
