### ISSUE TITLE
Cyverse paths should be generated by tags

### ISSUE THREAD

**Issue by equant** [phytooracle/automation#30]
Level 0 has this structure: `.../level_0/scanner3DTop/file_we_want.tar.gz` while all levels >0 have this structure: `.../level_0/scanner3DTop/2222-22-22/file_we_want.tar.gz`

Currently, the date is hardcoded into `distributed_pipeline_wrapper.py` and it breaks level 0 downloads.  The `distributed_pipeline_wrapper.py` needs logic to build the cyverse input/output paths from YAML keywords.

## `distributed_pipeline_wrapper.py` changes:

* For levels greater than zero, the file structure should be: `.../level_n/sensor_name/experiment_name/date/prefix_file_suffix`
* For level 0, the file structure should be: `.../level_n/sensor_name/prefix_file_suffix`

## YAML changes:

* Add `level`, `sensor_name` and `expirment` to YAML `tags` (top of file)
* move `basename` to under `cyverse`
* `output:subdir` becomes experiment (see issue #29).

**Comment by Travis-Simmons** [comment]
This bug is hindering module development for the new YAML pipelines.

**Comment by Travis-Simmons** [comment]
A temporary fix is:

## distributed_pipeline_wrapper.py changes:

### Delete date from line 146
irods_path = os.path.join(irods_path, (subdir if subdir else ""))

## YAML changes:
### level 0 downloads work as expected
### higher than 0, include ${DATE} at the end possibly (I am just developing for level 0 right now)?
      basename: /iplant/home/shared/phytooracle/season_10_lettuce_yr_2020/level_1/ps2Top/${DATE}

In your YAML change I think level should be starting_level since during processing we are going though multiple levels

**Comment by equant** [comment]
@emmanuelgonz Did you see @Travis-Simmons comment above?

> In your YAML change I think level should be starting_level since during processing we are going though multiple levels

I'm pretty sure when @emmanuelgonz and I discussed things, we were thinking that each yaml pipeline would only move from one level to the next (or stay in the same level).  I haven't thought about what "going through multiple levels" means.  If you go from level_0 to level_3, I don't think intermediary things can be saved to level_1 or level_2.

Here is an example of what the new YAML will have:

```
  cyverse:
    basename: /iplant/home/shared/phytooracle/
    input:
      level: level_0
      prefix: scanner3DTop-
      suffix: __*.tar.gz
    output:
      level: level_1
```

**Comment by emmanuelgonz** [comment]
@Travis-Simmons @equant Although we are oftentimes outputting processed data of various levels, I agree with @equant in that we cannot save intermediary things in their respective levels without (i) predefining levels before data processing (which will be difficult) and (ii) including multiple extra keys in the YAML. I think for the purposes of levels we should stick to the following:
- Level_0: Raw data straight from the gantry/drone platform
- Level_1: Processed data produced by PhytoOracle
- Level_2: Processed data produced after reprocessing/corrections
