### ISSUE TITLE
Should `experiment` be given on the command line?

### ISSUE THREAD

**Issue by equant** [phytooracle/automation#32]
Should `experiment` (e.g. sunflower, sorghum) be provided from the command line (instead of in the yaml)?  The `date` is taken from the command line.  Experiment is like date: it selects what specific data is chosen to be processed.

If experiment is defined in the yaml file, we will need a separate version of each version of the pipeline for each experiment.  So instead of:
```
├── season_11
│   ├── 3d_level_1_preprocessing.yaml
│   └── 3d_level_2_postprocessing.yaml
```
We would need
```
├── season_11
│   ├── 3d_level_1_preprocessing_sorghum.yaml
│   └── 3d_level_2_postprocessing_sorghum.yaml
│   └── 3d_level_1_preprocessing_yams.yaml
│   └── 3d_level_2_postprocessing_yams.yaml
```

**Comment by emmanuelgonz** [comment]
@equant I think we should make `experiment` a command line argument. Like you pointed out, it would reduce the number of YAMLs per growing season. We would want to account for those seasons that wouldn't have an experiment when it comes to compressing, bundling, and uploading outputs. An example of a season with no experiment tag would be season 10, we can either:

1. Set experiment = None
2. 3.Set experiment = lettuce
