### ISSUE TITLE
Rename season12_all_bucket_gcps.txt -> gcp_season_12.txt

### ISSUE THREAD

**Issue by equant** [phytooracle/automation#33]
When I try to rename `season12_all_bucket_gcps.txt` it fails without any clear reason.  I don't know if it's permission related.  @Travis-Simmons can you try to rename it to `gcp_season_12.txt` for me?

https://de.cyverse.org/data/ds/iplant/home/shared/phytooracle/season_12_sorghum_soybean_sunflower_tepary_yr_2021/level_0/necessary_files?selectedOrder=asc&selectedOrderBy=name&selectedPage=0&selectedRowsPerPage=100

**Comment by Travis-Simmons** [comment]
season12_all_bucket_gcps.txt renamed to gcp_season_12.txt
