### ISSUE TITLE
Standardize command/input/output $VARIABLES and make thir replacement a function in generate_makeflow_json 

### ISSUE THREAD

**Issue by Travis-Simmons** [phytooracle/automation#36]
Currently there is a long string of .replace statements in each line of the generate_makeflow_json function. This could be a standardized dictionary that parses all the commands, inputs, and outputs.

**Comment by equant** [comment]
@emmanuelgonz and I talked about this today.  I agree that this would be an improvement, but I think implementing it and testing it is quite an expensive endeavor.

**Comment by Travis-Simmons** [comment]
I believe not standardizing the variable names will complicate things heavily. When we get to generate_makeflow_json no matter the sensor the command, input, and output $variable_names should be parsed in the same way. If not we run into problems like below:

in the if sensor=='scannner3DTop' portion, $UUID is parsed as out.replace('$UUID', '_'.join(os.path.basename(file).split('_')[:2])

If i need to use a similar variable in another sensor i am going to end up having to add it on the end and do something like:
out.replace('$UUID', '_'.join(os.path.basename(file).split('_')[:2]).replace($PSII_UUID, os.path.basename(file).split('_')[0] )

this would be very confusing for someone trying to add in new modules or sensors. Instead we could make generate_makeflow_json work something like this:

def replace_all(text, dic):
    for i, j in dic.items():
        text = text.replace(i, j)
    return text

def generate_makeflow_json(all_the_current_args):

    jx_dict = {
                        "rules": []
    }

    rules = []
  
    for file in files:
    
        variable_dict = {
            'command_variables':
                {'$3D_UUID' :  '_'.join(os.path.basename(file).split('_')[:2],
                'PSII_UUID' : os.path.basename(file).split('_')[0]},

            'output_variables':
                {'$an_output': 'a_command'},

            'input_variables':
                {'$an_output': 'a_command'}
        }

        command = replace_all(command, variable_dict['command_variables'])

        output_list = [replace_all(i, variable_dict['output_variables']) for i in outputs]

        input_list = [replace_all(i, variable_dict['input_variables']) for i in inputs]

        a_rule = {
            "command" : timeout + command
            "outputs" : output_list
            "inputs"  : [container, 
                        seg_model_name, 
                        det_model_name] + input_list}

        rules.append(a_rule)
    
    jx_dict['rules'] = rules


# --------------------------------------------
In this way, if someone ever wants to add a new variable, they just add it to the one dictionary and everything is parsed properly.
