### ISSUE TITLE
Running a whole date of psii deleted my wrapper script as well as everything in the directory containing the yaml used.

### ISSUE THREAD

**Issue by Travis-Simmons** [phytooracle/automation#45]

**Comment by emmanuelgonz** [comment]
The automation script calls onto specific directories/files for deletion. You can check out the function called `clean_inputs`. It is normal for it to delete raw data, but it would not delete your working directory (`automation`) nor your yaml script directory (`automation/yaml_files/`). If you ran this as a batch job, I would check your batch script.

**Comment by emmanuelgonz** [comment]
Unable to recreate. The deletion may have been due to SLURM job scheduling instead of PhytoOracle automation script.
