### ISSUE TITLE
distributed_pipeline_wrapper.py continues even when there is a YAML error

### ISSUE THREAD

**Issue by equant** [phytooracle/automation#47]
The current code looks like this...

```
            try:
                global dictionary
                dictionary = yaml.safe_load(stream)
                build_containers(dictionary)
            except yaml.YAMLError as exc:
                print(exc)
```
@emmanuelgonz Is there a reason why `distributed_pipeline_wrapper.py` continues when there's an error loading the YAML file?  In my current branch I'd like to just have the YAMLError just throw it's exception and quit, but I don't want to implement that if there's some case I'm not considering.  Thanks.

**Comment by emmanuelgonz** [comment]
@equant I have no concern with having a YAMLError throwing an exception and quitting, I think this would be an improvement and should be implemented. The current code doesn't error out and results in empty directories being tarred and uploaded to CyVerse, this was done as a way to indicate the status of "pipeline ran, it failed, and we have to figure out what went wrong."

**Comment by equant** [comment]
Great.  This will be part of the `38-fetchuntar-dir-contents` branch.
