### ISSUE TITLE
dictionary['paths']['cyverse']['output']['subdir'] isn't used.

### ISSUE THREAD

**Issue by equant** [phytooracle/automation#6]
YAML files provide (e.g. `rnaseq_spectral.yaml` `example_machinelearning_workflow_plant_vol.yaml`)  provide the config `['paths']['cyverse']['output']['subdir']`.  This doesn't seem to be used? It shows up in `upload_outputs()` but it doesn't seem to be used.  Should we remove this from YAML examples, or do we need to implement this feature or am I wrong that it's not used somewhere?

**Comment by emmanuelgonz** [comment]
You are right, this is not used. We may want to add an if/else statement to account for cases where users do provide this YAML field.

**Comment by equant** [comment]
This is being solved by #30
