### ISSUE TITLE
Suffix is no longer working for season 10

### ISSUE THREAD

**Issue by emmanuelgonz** [phytooracle/automation#73]
The key ['paths']['cyverse']['input']['suffix'] is no longer working. Even if this key is provided, the entire ['paths']['cyverse']['input']['input_dir'] is downloaded. This is an issue for season 10 reprocessing, as we only need `/iplant/home/shared/phytooracle/season_10_lettuce_yr_2020/level_2/scanner3DTop/2020-02-28/individual_plants_out/2020-02-28_segmentation_pointclouds_plants.tar` not the entire `/iplant/home/shared/phytooracle/season_10_lettuce_yr_2020/level_2/scanner3DTop/2020-02-28/individual_plants_out/`.

The YAML being used for testing is `yaml_files/season_10/example_machinelearning_workflow_normalization_open3d_fixes.yaml`.

**Comment by equant** [comment]
@emmanuelgonz I see you created a branch for this.  Are you planning on working on it?  I can work on it tomorrow if you want.

**Comment by equant** [comment]
Re-reading this...  Can I see the yaml file that is being used?  It might work if you remove input_dir.  Take a look at the comment I made for issue #61 ...  You can have either prefixes and suffixes, **or** input_dir, but not both.

**Comment by emmanuelgonz** [comment]
@equant The yaml file being used is `yaml_files/season_10/example_machinelearning_workflow_normalization_open3d_fixes.yaml`. I believe in this case, we need `input_dir` which is included in the YAML file, otherwise, suffix would not be specific enough without `input_dir`. Essentially, we need the ability to download a single tarball within `input_dir` which would be specified by `suffix`.

**Comment by equant** [comment]
Cool.  Thanks, that should get me started.

**Comment by equant** [comment]
This was merged into main.  It needs to be tested for Season 11 before it should be closed.
