### ISSUE TITLE
get_gcp_file() doesn't work for all seasons

### ISSUE THREAD

**Issue by equant** [phytooracle/automation#8]
I think that this function doesn't need to be modified, however, it I expect that it won't work because the gcp files on cyverse aren't in the same place from season to season (e.g. compare 10 and 11).  GCP files for seasons 11-13 need to be moved to where this function expects them to be.

**Comment by Travis-Simmons** [comment]
I will be creating a '/level_0/necessary_files' directory for each season and moving the GCP files there. Currently, I am waiting to be given write/delete permissions in those directories.

**Comment by Travis-Simmons** [comment]
Done for season 11

**Comment by Travis-Simmons** [comment]
Fixed for seasons 11 and 12. When we create a directory for 13 we will be sure that it follows convention.
