### ISSUE TITLE
Remove defunct functions from `distributed_pipeline_wrapper.py`

### ISSUE THREAD

**Issue by equant** [phytooracle/automation#83]
The following functions in the `distributed_pipeline_wrapper` script appear to be unused.  I'm looking to see if anyone knows any reason that they should not be removed from the code...

```
download_level_1_data()
get_transformation_file()
get_bundle_dir()
get_bundle_json()
```

**Comment by emmanuelgonz** [comment]
@equant I cannot think of any reason to keep them around. I am all for getting rid of these defunct functions.
